-- test xpass/xfail with an explicit pass
test.xfail()

pass("this is an unexpected pass")
